name: RpgCraft
version: 1.0
main: fr.jeunesauvage.RpgCraft
api-version: 1.21
author: jeunesauvage
depend: [ProtocolLib, Citizens, BetonQuest, SkinsRestorer]
# depend: [ProtocolLib, Citizens, Sentinel, BetonQuest, WorldEdit, WorldGuard, SkinsRestorer]

commands:
  # npc commands
  placemynpc:
    description: give placer to player
    usage: /placemynpc
    permission: rpgcraft.op
  createmynpc:
    description: create npc using placer
    usage: /createmynpc <npc name>
    permission: rpgcraft.op
  levelmynpc:
    description: change level of npc
    usage: /levelmynpc <level> <npc name>
    permission: rpgcraft.op
  patrolmynpc:
    description: change patrol range of npc
    usage: /patrolmynpc <patrol range> <npc name>
    permission: rpgcraft.op
  aggromynpc:
    description: change aggro range of npc
    usage: /aggromynpc <aggro range> <npc name>
    permission: rpgcraft.op
  chasemynpc:
    description: change chase range of npc
    usage: /chasemynpc <chase range> <npc name>
    permission: rpgcraft.op
  bossmynpc:
    description: change boss of npc
    usage: /bossmynpc <is boss> <npc name>
    permission: rpgcraft.op
  equipmynpc:
    description: equip main item to npc
    usage: /equipmynpc <npc name>
    permission: rpgcraft.op
  teammynpc:
    description: add/remove team to npc
    usage: /teammynpc <action> <team> <npc name>
    permission: rpgcraft.op
  dropmynpc:
    description: change drop to npc
    usage: /dropmynpc <drop> <npc name>
    permission: rpgcraft.op
  templatemynpc:
    description: change template to npc
    usage: /templatemynpc <template> <npc name>
    permission: rpgcraft.op
  spawnmynpc:
    description: spawn npc
    usage: /spawnmynpc <npc name>
    permission: rpgcraft.op
  despawnmynpc:
    description: despawn npc
    usage: /despawnmynpc <npc name>
    permission: rpgcraft.op
  deletemynpc:
    description: delete npc
    usage: /deletemynpc <npc name>
    permission: rpgcraft.op
  # item command
  giveequipable:
    description: give item to player
    usage: /giveequipable <player name> <item id>
    permission: rpgcraft.op
  givespell:
    description: give item to player
    usage: /givespell <player name> <item id>
    permission: rpgcraft.op
  givepotion:
    description: give item to player
    usage: /givepotion <player name> <item id>
    permission: rpgcraft.op
  # player command
  menu:
    description: open menu
    usage: /menu <player name/UUID>
    permission: rpgcraft.everyone
  # sound command
  quote:
    description: play quote
    usage: /quote
    permission: rpgcraft.everyone
  quotegreeting:
    description: play quote greeting
    usage: /quotegreeting
    permission: rpgcraft.everyone
  quotefarewell:
    description: play quote farewell
    usage: /quotefarewell
    permission: rpgcraft.everyone
  quoteattack:
    description: play quote attack
    usage: /quoteattack
    permission: rpgcraft.everyone
  quotedeath:
    description: play quote death
    usage: /quotedeath
    permission: rpgcraft.everyone
  # group command
  group:
    description: group menu / group invite
    usage: /group <player name>
    permission: rpgcraft.everyone
  groupaccept:
    description: accept invite
    usage: /groupaccept
    permission: rpgcraft.everyone
  groupdecline:
    description: decline invite
    usage: /groupdecline
    permission: rpgcraft.everyone
  groupquit:
    description: quit group
    usage: /groupquit
    permission: rpgcraft.everyone
  # world command
  cleanentities:
    description: clean all entities in alls worlds
    usage: /cleanentities
    permission: rpgcraft.op

permissions:
  rpgcraft.op:
    default: op
  rpgcraft.everyone:
    default: true